[package]
name = "ax"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
dirs = "6.0.0"
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ureq = { version = "3.4.0", features = ["json"] }
usage = { version = "6", package = "usage-rs", features = ["completions"] }
